const Admin = () => {
  return <div>Admin login</div>;
};

export default Admin;

// write meta data in layout.js or here as dynamic metadata
export async function generateMetadata({ params }) {
  // this is used if this was a dynamic  route because it is not so params obj is empty
  return {
    title: "Admin: Login Page",
    description: "Admin is using: Generated by create next app",
  };
}
