export const metadata = {
  title: "Admin: Create Next App",
  description: "Admin is using: Generated by create next app",
};

// children are files in this folder
export default function AdminLayout({ children }) {
  return (
    <>
      <p> This is the layout in admin Logout</p>
      {children}
    </>
  );
}
