export const metadata = {
  title: "Admin: Create Next App",
  description: "Admin is using: Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
      <span className="bg-gray-700 w-full">Admin Navbar</span>
      {children}
      <span className="bg-gray-700 w-full">Admin Footer</span>
    </>
  );
}
